// Mapping from ENERJIMMY exercise name (as seeded in prisma/seed.ts) to a matched
// illustration slug from the @bryllim/workout-guide dataset (Everkinetic-derived
// artwork, CC BY-SA 4.0). Not every exercise has a confident match -- exercises
// absent from this map fall back to the original silhouette icons in
// components/icons.tsx. See CREDITS.md for full attribution.

export const EXERCISE_IMAGE_SLUG: Record<string, string> = {
  "Abdominales bicicleta": "bicycle-crunch",
  "Abduccion de cadera con banda": "banded-standing-hip-abduction",
  "Abduccion de cadera en maquina": "hip-abduction-machine",
  "Aperturas con mancuernas": "dumbbell-fly",
  "Assault bike": "assault-bike",
  "Battle ropes (cuerdas de batalla)": "battle-ropes",
  "Bicicleta estatica": "cycling",
  "Buenos dias con barra": "good-morning",
  "Burpee con press de mancuernas": "burpee",
  "Burpees": "burpee",
  "Carrera en cinta": "running",
  "Contractor de pecho (pec deck)": "pec-deck",
  "Cruce de poleas (crossover)": "cable-fly",
  "Cruce de poleas bajo a alto": "incline-cable-fly",
  "Crunch en polea alta (de rodillas)": "cable-crunch",
  "Curl concentrado con mancuerna": "concentration-curl",
  "Curl de biceps con barra Z": "ez-bar-curl",
  "Curl de biceps con mancuernas": "bicep-curl",
  "Curl de biceps en polea baja": "cable-curl",
  "Curl en banco Scott con barra Z": "preacher-curl",
  "Curl en banco Scott con mancuerna": "preacher-curl",
  "Curl femoral de pie en maquina": "leg-curl",
  "Curl femoral sentado en maquina": "seated-leg-curl",
  "Curl femoral tumbado en maquina": "lying-leg-curl",
  "Curl inverso con barra": "reverse-curl",
  "Curl martillo con mancuernas": "hammer-curl",
  "Curl nordico": "nordic-hamstring-curl",
  "Dead bug": "dead-bug",
  "Dominadas": "pull-up",
  "Dominadas supinas (chin-up)": "chin-up",
  "Elevacion de piernas colgado": "hanging-leg-raise",
  "Elevacion de piernas tumbado": "lying-leg-raise",
  "Elevacion de rodillas colgado": "hanging-knee-raise",
  "Elevacion de talones a una pierna (peso corporal)": "single-leg-calf-raise",
  "Elevacion de talones con mancuernas": "calf-raise",
  "Elevacion de talones de pie en maquina": "standing-calf-raise",
  "Elevacion de talones en prensa de piernas": "leg-press-calf-raise",
  "Elevacion de talones sentado en maquina": "seated-calf-raise",
  "Elevaciones frontales con mancuernas": "front-raise",
  "Elevaciones laterales con mancuernas": "lateral-raise",
  "Elevaciones laterales en polea": "cable-lateral-raise",
  "Elevaciones posteriores en maquina (peck deck inverso)": "reverse-pec-deck",
  "Eliptica": "elliptical",
  "Encogimientos abdominales (crunch)": "crunch",
  "Encogimientos de trapecio con barra": "shrug",
  "Encogimientos de trapecio con mancuernas": "dumbbell-shrug",
  "Escaladora (stair climber)": "stair-climber",
  "Extension de cuadriceps en maquina": "leg-extension",
  "Extension de triceps en polea (barra)": "tricep-pushdown",
  "Extension de triceps en polea (cuerda)": "rope-tricep-pushdown",
  "Extension de triceps en polea alta a un brazo": "overhead-tricep-extension",
  "Extension de triceps sobre la cabeza con mancuerna": "dumbbell-overhead-tricep-extension",
  "Face pull con banda": "banded-face-pull",
  "Face pull en polea": "face-pull",
  "Farmer's walk con kettlebells": "farmer-carry",
  "Farmer's walk con mancuernas": "farmer-carry",
  "Flexiones de brazos": "push-up",
  "Flexiones declinadas (manos elevadas)": "incline-push-up",
  "Flexiones inclinadas (pies elevados)": "decline-push-up",
  "Flexiones pike (pino)": "pike-push-up",
  "Fondos en banco (triceps)": "bench-dip",
  "Fondos en paralelas (pecho)": "chest-dip",
  "Fondos en paralelas (triceps)": "dip",
  "Giros rusos con kettlebell": "russian-twist",
  "Giros rusos con mancuerna": "weighted-russian-twist",
  "Hip thrust con barra": "hip-thrust",
  "Hiperextensiones lumbares": "back-extension",
  "Jalon al pecho en polea": "lat-pulldown",
  "Jalon con agarre cerrado en polea": "close-grip-lat-pulldown",
  "Jumping jacks": "jumping-jack",
  "Mountain climbers": "mountain-climber",
  "Pajaros (elevaciones posteriores) con mancuernas": "rear-delt-fly",
  "Pallof press con banda": "banded-pallof-press",
  "Pallof press en polea": "pallof-press",
  "Patada de burro (donkey kick)": "donkey-kick",
  "Patada de gluteo en maquina": "machine-glute-kickback",
  "Patada de gluteo en polea": "cable-kickback",
  "Patada de triceps con mancuerna": "tricep-kickback",
  "Peso muerto a una pierna con mancuerna": "single-leg-romanian-deadlift",
  "Peso muerto convencional": "deadlift",
  "Peso muerto piernas rigidas con mancuernas": "dumbbell-romanian-deadlift",
  "Peso muerto rumano con barra": "romanian-deadlift",
  "Peso muerto rumano con barra (isquios)": "romanian-deadlift",
  "Peso muerto rumano con kettlebell": "kettlebell-romanian-deadlift",
  "Peso muerto rumano con mancuernas": "dumbbell-romanian-deadlift",
  "Peso muerto sumo": "sumo-deadlift",
  "Plancha abdominal": "plank",
  "Plancha con toque de hombro": "plank-shoulder-tap",
  "Plancha lateral": "side-plank",
  "Prensa de piernas": "leg-press",
  "Press Arnold": "arnold-press",
  "Press cerrado con barra": "close-grip-bench-press",
  "Press de banca con barra": "bench-press",
  "Press de banca con mancuernas": "dumbbell-bench-press",
  "Press de banca declinado con barra": "decline-bench-press",
  "Press de banca inclinado con barra": "incline-bench-press",
  "Press de hombros en maquina": "machine-shoulder-press",
  "Press de pecho en maquina": "machine-chest-press",
  "Press declinado con mancuernas": "decline-dumbbell-press",
  "Press frances con barra Z": "skull-crusher",
  "Press frances con mancuerna": "dumbbell-skull-crusher",
  "Press inclinado con mancuernas": "incline-dumbbell-press",
  "Press militar con barra": "overhead-press",
  "Press militar con mancuernas": "standing-dumbbell-press",
  "Puente de gluteo-isquios con balon (nordic curl asistido)": "stability-ball-hamstring-curl",
  "Puente de gluteos con mancuerna": "dumbbell-glute-bridge",
  "Puente de gluteos en el suelo": "glute-bridge",
  "Remo Pendlay": "pendlay-row",
  "Remo al menton con barra": "upright-row",
  "Remo con banda de resistencia": "banded-row",
  "Remo con barra": "barbell-row",
  "Remo con dos mancuernas": "dumbbell-bent-over-row",
  "Remo con mancuerna a un brazo": "one-arm-dumbbell-row",
  "Remo en T con barra": "t-bar-row",
  "Remo en maquina (cardio)": "rowing",
  "Remo en maquina sentado": "machine-row",
  "Remo en polea baja sentado": "seated-row",
  "Remo invertido (australian pull-up)": "inverted-row",
  "Rueda abdominal (ab wheel)": "ab-wheel",
  "Saltos de cuerda": "jump-rope",
  "Saltos de cuerda (gemelos)": "jump-rope",
  "Sentadilla bulgara con mancuernas": "bulgarian-split-squat",
  "Sentadilla con kettlebell (goblet)": "goblet-squat",
  "Sentadilla con salto": "jump-squat",
  "Sentadilla en multipower (Smith)": "smith-machine-squat",
  "Sentadilla frontal con barra": "front-squat",
  "Sentadilla goblet con mancuerna": "goblet-squat",
  "Sentadilla hack en maquina": "hack-squat",
  "Sentadilla sissy": "sissy-squat",
  "Sentadilla sumo con mancuerna": "dumbbell-sumo-squat",
  "Sentadilla trasera con barra": "squat",
  "Sprints en cinta": "running",
  "Step-up con mancuernas": "step-up",
  "Swing a dos manos con kettlebell": "kettlebell-swing",
  "Swing con kettlebell": "kettlebell-swing",
  "Zancada inversa con mancuernas": "reverse-lunge",
  "Zancadas caminando con mancuernas": "walking-lunge",
  "Zancadas estaticas con mancuernas": "split-squat",
};

/** Public path to the illustration for an exercise name, or null if unmatched. */
export function getExerciseImage(name: string): string | null {
  const slug = EXERCISE_IMAGE_SLUG[name];
  return slug ? `/exercise-images/${slug}.png` : null;
}

